### ISSUE TITLE
Проверка

### ISSUE THREAD

**Issue by DanaZL** [AZuev1986/lp_lesson2#5]
https://github.com/AZuev1986/lp_lesson2/blob/f0704e2ed17356832bbaa5360abf25a74563252f/bot.py#L33

Я думаю, здесь стоит сделать проверку на корректность введенных данных с помощию if, мы же знаем все планеты, которые умеет обрабатывать ephem

**Comment by AntZuev** [comment]
в том то и проблема, что не знал точно. я же задавал вопрос про полный список атрибутов и было исключение в виде Земли, плюс проблемы со спутниками, которые я не понял как запрашивать, поэтому я решил что будет правильнее обрабытывать все при помощи getattr плюс сделать обработчик исключения, если пользователь неверно ввел данные, и еще это казалось лучше чем 7  if

**Comment by DanaZL** [comment]
Согласна с тем, что это лучше чем 7 if и что исключение тоже выход. В качестве альтернативы можно было бы, например, создать один список со всеми планетами - и проверять введенную пользователем строку на то, что она есть в этом списке
