### ISSUE TITLE
/planet <Планета>

### ISSUE THREAD

**Issue by DanaZL** [AZuev1986/lp_lesson2#6]
https://github.com/AZuev1986/lp_lesson2/blob/f0704e2ed17356832bbaa5360abf25a74563252f/bot.py#L49

В задании требуется, чтобы команда для бота /planet  принимала на вход имя планеты, т.е. команда должна выглядеть так:
/planet Mars
у тебя сейчас бот ждет, пока пользователь отправит имя планеты следующим сообщением

**Comment by AntZuev** [comment]
Похоже что я неправильно понял задание из-за этой строки в задании "Добавьте в бота команду /planet, которая будет принимать на вход название планеты на английском, например /ephem Mars"
Для себя я подумал - что надо сначала в каком-то виде создать и использовать команду /planet, а  /ephem Mars - это просто один из вариантов запроса планеты, возможно стоит в задании так и написать что для ввода планеты использовать формат ''/planet Название планеты"

**Comment by DanaZL** [comment]
поняла, передам оргам на будущее
